# Generated by Django 5.0.7 on 2025-12-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('icon', models.CharField(default='/static/icons/icon-192x192.png', max_length=100, verbose_name='Ícone')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=20, verbose_name='Frequência')),
                ('scheduled_time', models.TimeField(verbose_name='Horário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Último Envio')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Envio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notificação Agendada',
                'verbose_name_plural': 'Notificações Agendadas',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Chave P256DH')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth Secret')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Subscrição Push',
                'verbose_name_plural': 'Subscrições Push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('icon', models.CharField(default='/static/icons/icon-192x192.png', max_length=200, verbose_name='Ícone')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.pushsubscription', verbose_name='Subscrição')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='core_pushsu_user_id_35c075_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['endpoint'], name='core_pushsu_endpoin_0a3bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['subscription', 'status'], name='core_pushno_subscri_848c76_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['created_at'], name='core_pushno_created_851efd_idx'),
        ),
    ]
