# Generated by Django 5.0.7 on 2025-12-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_webauthncredential'),
    ]

    operations = [
    ]
