# Generated by Django 5.2.6 on 2025-09-23 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Orçamento Total')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Gasto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('forecast_type', models.CharField(choices=[('cash_flow', 'Fluxo de Caixa'), ('revenue', 'Receita'), ('expenses', 'Despesas'), ('balance', 'Saldo')], max_length=20, verbose_name='Tipo')),
                ('period_type', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('data', models.JSONField(default=dict, verbose_name='Dados')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisão (%)')),
                ('model_parameters', models.JSONField(default=dict, verbose_name='Parâmetros do Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Previsão',
                'verbose_name_plural': 'Previsões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('cash_flow', 'Fluxo de Caixa'), ('income_statement', 'Demonstrativo de Resultado'), ('balance_sheet', 'Balanço Patrimonial'), ('category_analysis', 'Análise por Categoria'), ('trends', 'Análise de Tendências'), ('goals_progress', 'Progresso de Metas'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtros')),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('ready', 'Pronto'), ('error', 'Erro')], default='generating', max_length=20, verbose_name='Status')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='Arquivo PDF')),
                ('file_excel', models.FileField(blank=True, null=True, upload_to='reports/excel/', verbose_name='Arquivo Excel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('alert_type', models.CharField(choices=[('low_balance', 'Saldo Baixo'), ('goal_deadline', 'Prazo de Meta'), ('overdue_transaction', 'Transação Vencida'), ('budget_exceeded', 'Orçamento Excedido'), ('unusual_expense', 'Gasto Incomum'), ('cash_flow_negative', 'Fluxo de Caixa Negativo'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10, verbose_name='Severidade')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido'), ('dismissed', 'Dispensado')], default='active', max_length=20, verbose_name='Status')),
                ('related_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Relacionados')),
                ('action_url', models.URLField(blank=True, verbose_name='URL de Ação')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Disparado em')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='reports_ale_company_68e7c5_idx'), models.Index(fields=['user', 'status'], name='reports_ale_user_id_d41faa_idx'), models.Index(fields=['alert_type', 'severity'], name='reports_ale_alert_t_16fb95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('layout', models.JSONField(default=dict, verbose_name='Layout')),
                ('widgets', models.JSONField(default=list, verbose_name='Widgets')),
                ('refresh_interval', models.IntegerField(default=30, verbose_name='Intervalo de Atualização (minutos)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dashboard Padrão')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
