# Generated by Django 5.0.7 on 2025-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('cash_flow', 'Fluxo de Caixa'), ('income_statement', 'Demonstrativo de Resultado'), ('balance_sheet', 'Balanço Patrimonial'), ('category_analysis', 'Análise por Categoria'), ('trends', 'Análise de Tendências'), ('goals_progress', 'Progresso de Metas'), ('dasn_simei', 'DASN-SIMEI (Declaração Anual MEI)'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
